sonar.organization=upt-faing-epis
sonar.projectKey=UPT-FAING-EPIS_lab-2026-i-si784-u1-04-cs-mauchoquenachoque
sonar.projectName=lab-2026-i-si784-u1-04-cs-mauchoquenachoque
sonar.sources=Shorten
sonar.tests=Shorten/Shorten.Tests
sonar.host.url=https://sonarcloud.io
